# Generated by Django 2.2.6 on 2019-10-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
